name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./kiss.sh build -o ./kiss

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: kiss
          if-no-files-found: error
