name: reinstall

on: [workflow_dispatch]

jobs:
  reinstall:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to `known_hosts`
        run: |
          ssh-keyscan -H "${SSH_HOST}" >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Build
        run: ./kiss.sh build -o ./kiss

      - name: Reinstall
        run: |
          ./kiss ssh -i ~/.ssh/id_rsa "${SSH_DEST}" backup -o ./kiss.bak &&
          ./kiss ssh -i ~/.ssh/id_rsa "${SSH_DEST}" uninstall \
            -e "${KISS_EMAIL}" -d "${KISS_DOMAIN}" &&
          ./kiss ssh -i ~/.ssh/id_rsa "${SSH_DEST}" recreate ./kiss.bak \
            -e "${KISS_EMAIL}" -d "${KISS_DOMAIN}"
        env:
          SSH_DEST: ${{ secrets.SSH_USER || 'root' }}@${{ secrets.SSH_HOST }}
          KISS_EMAIL: ${{ secrets.KISS_EMAIL }}
          KISS_DOMAIN: ${{ secrets.KISS_DOMAIN }}

      - name: Cleanup
        if: always()
        run: |
          [ -f ~/.ssh/id_rsa ] && shred -fuz ~/.ssh/id_rsa && echo "Shredded 'id_rsa'"
          [ -f ./kiss.bak ] && shred -fuz ./kiss.bak && echo "Shredded 'kiss.bak'"
          :
