name: release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./kiss.sh build -o ./kiss

      - name: Upload build artifacts to GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: kiss
          github-token: ${{ secrets.GITHUB_TOKEN }}
